### ISSUE TITLE
Server crashes after placing a scroll in survival

### ISSUE THREAD

**Issue by ghost** [billythegoat101/Runic-Dust-Mod#2]
After placing a scroll (doesn't matter which) in Survival on a server, the server crashes.
In Creative everything went fine, but (in this case) the rune of wisdom didn't work properly.

---

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 10.08.13 13:16
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_71052_bv()I
    at dustmod.ItemPlaceScroll.func_77648_a(ItemPlaceScroll.java:73)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:149)
    at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:425)
    at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:553)
    at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:461)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:134)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:677)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 657862864 bytes (627 MB) / 765853696 bytes (730 MB) up to 1888419840 bytes (1800 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 2130 (119280 bytes; 0 MB) allocated, 1933 (108248 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.51 FML v5.2.23.738 Minecraft Forge 7.8.1.738 18 mods loaded, 18 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.23.738} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.1.738} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{0.1.36} [Galacticraft Core](Galacticraft-1.5.2-a0.1.36.410.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CC.CocoaCraft{1.61} [CocoaCraft](CocoaCraft1.61[1.5.2].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DustMod{1.3.2} [Runic Dust Mod](dustmod-v1.3.2_CORE.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DustModDefaults{1.6.2} [Runic Dust Mod: Default runes and inscriptions pack](dustmod-v1.6.2_DEFAULT-RUNES.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hotfix1{0.0.1} [Hotfix-Dustmod](hotfix-dustmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ICBM|Contraption{1.2.1} [ICBM](ICBM_Contraption_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ICBM|Sentry{1.2.1} [ICBM](ICBM_Sentry_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ICBM|Explosion{1.2.1} [ICBM](ICBM_Explosion_v1.2.1.172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    musiccraft{2.0.01} [MusicCraft](MusicCraft 2.0.01 [1.5.2] Server.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{3.0.5h1} [Thaumcraft](Thaumcraft3.0.5h.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.4.6.0} [Thermal Expansion](ThermalExpansion-2.4.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{1.5.2 v1.12.0} [Balkon's WeaponMod](WeaponMod v1.12.0_srg.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 910 (50960 bytes; 0 MB) allocated, 868 (48608 bytes; 0 MB) used
    Player Count: 1 / 20; [GCCorePlayerMP['sx9'/280, l='world', x=-439,71, y=66,00, z=219,27]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by ghost** [comment]
I guess it's because the function func_71052_bv is obsolete and is now called getItemInUseCount.

func_71052_bv,getItemInUseCount,2,Returns the item in use count
https://github.com/keepcalm/BukkitForge/blob/master/porting/mappings/v1_5_R2/mcp/methods.csv
